### PR TITLE
Add session id to Session cmds, when appropriate 

### PR DESCRIPTION
**Pull request by askedrelic**
Starting on fixing #64.

### CODE REVIEW

**Comment by tony** [comment]
Let's try to take the approach where we smooth out the `*args` (https://github.com/tony/libtmux/issues/64#issuecomment-321177837). We can use `+=` instead of `.extends(` to avoid an extra function call (https://github.com/tony/libtmux/issues/64#issuecomment-321397704).

**Comment by askedrelic** [comment]
So I rebased my code to use `+=` to add the session id, if it is not set. It's a little more complicated due to tmux requiring the `-t` arg be in a specific position, but the test suite should be passing!

**Comment by askedrelic** [comment]
Hmm looks like tests broke due to Py3. I'm still using Py2 as my main environment, I will take a look!

**Comment by tony** [comment]
@askedrelic nice job!

**Comment by askedrelic** [comment]
Hooray, thanks for the merge @tony 🎊

**Comment by tony** [comment]
released in v0.7.4

**Pull request merged**
