### PR TITLE
allow splitting panes horizontally

### PR DESCRIPTION
**Pull request by tek**
`vertical` parameter for `split_window()`, defaulting to True

### CODE REVIEW

**Comment by tony** [comment]
@tek 

Can you add tests for vertical/non-vertical splits?

**Comment by tek** [comment]
there you go!

**Comment by tony** [comment]
merged, do you need this in a project?  I can bump the pypi version up if you wish

**Comment by tek** [comment]
it's going to be a while until I make a release, so don't worry about it

**Pull request merged**
